import type {ImageSourcePropType} from 'react-native';

export type BiigctsandbyonndCat = {
  id: string;
  name: string;
  scientificName: string;
  status: string;
  tag: string;
  description: string;
  speed: string;
  weight: string;
  size: string;
  diet: string;
  naturalHabitat: string;
  conservationStatus: string;
  conservationNote: string;
  facts: string[];
  image: ImageSourcePropType | null;
};

export const biigctsandbyonndCats: BiigctsandbyonndCat[] = [
  {
    id: 'bengal_tiger',
    scientificName: 'Panthera tigris',
    name: 'Bengal Tiger',
    status: 'Endangered',
    tag: 'Apex Predator',
    description:
      'The Bengal tiger is one of the most iconic big cats in the world, known for its powerful body, deep orange coat, bold black stripes, and intense golden eyes. It is the most numerous tiger subspecies, yet it still faces serious threats from habitat loss, poaching, and conflict with humans.',
    speed: '49–65 km/h',
    weight: '140–300 kg',
    size: '270–310 cm body length',
    diet: 'Deer, wild boar, water buffalo, monkeys',
    naturalHabitat: 'Tropical and subtropical forests, mangroves, grasslands',
    conservationStatus: 'Endangered',
    conservationNote: 'Monitored by IUCN Red List',
    facts: [
      'No two Bengal tigers have the same stripe pattern — each one is as unique as a human fingerprint.',
      'Bengal tigers are excellent swimmers and may cross rivers or flooded forest areas with ease.',
      'A tiger’s roar can be heard from several kilometers away.',
      'They usually hunt alone, most often at dusk, dawn, or during the night.',
      'The Sundarbans mangrove forest is one of the most famous places where Bengal tigers live.',
    ],
    image: null,
  },
  {
    id: 'african_lion',
    scientificName: 'Panthera leo',
    name: 'African Lion',
    status: 'Vulnerable',
    tag: 'Pride Leader',
    description:
      'The African lion is one of the most recognizable animals on Earth, often called the “king of beasts” because of its impressive mane, deep roar, and powerful presence. Unlike most big cats, lions are highly social and live in groups called prides, where females, cubs, and a small number of males share territory and protection.',
    speed: '60–80 km/h in short bursts',
    weight: '120–250 kg',
    size: '240–330 cm body length including tail',
    diet: 'Zebras, wildebeest, antelope, buffalo, warthogs',
    naturalHabitat: 'Savannahs, grasslands, open woodlands, dry scrublands',
    conservationStatus: 'Vulnerable',
    conservationNote: 'Monitored by IUCN Red List',
    facts: [
      'Lions are the only big cats that live in large social groups called prides.',
      'A lion’s roar can travel across open landscapes and be heard from far away.',
      'Lionesses do most of the hunting for the pride.',
      'Male lions use their mane to appear larger and stronger to rivals.',
      'Lions spend much of the day resting to save energy for hunting and territory patrols.',
      'White lions are not albino; their pale color comes from a rare genetic trait.',
    ],
    image: null,
  },
  {
    id: 'amur_tiger',
    scientificName: 'Panthera tigris altaica',
    name: 'Amur Tiger',
    status: 'Endangered',
    tag: 'Frozen Forest Giant',
    description:
      'The Amur tiger, also known as the Siberian tiger, is the largest tiger subspecies and one of the most powerful cats on the planet. It lives in cold forests of the Russian Far East and nearby regions, where snow, mountains, and dense woodland shape its daily survival.',
    speed: '50–65 km/h',
    weight: '160–320 kg',
    size: '280–330 cm body length including tail',
    diet: 'Deer, wild boar, elk, hares, smaller mammals',
    naturalHabitat: 'Cold temperate forests, snowy taiga, mountain forests',
    conservationStatus: 'Endangered',
    conservationNote: 'Monitored by IUCN Red List',
    facts: [
      'The Amur tiger is considered the largest living wild cat.',
      'Its thick winter coat helps protect it from extreme cold.',
      'Amur tigers need very large territories to find enough prey.',
      'Their paw prints can be huge and are often visible in snow.',
      'They are powerful swimmers despite living in cold northern forests.',
    ],
    image: null,
  },
  {
    id: 'jaguar',
    scientificName: 'Panthera onca',
    name: 'Jaguar',
    status: 'Near Threatened',
    tag: 'Jungle Crusher',
    description:
      'The jaguar is the largest cat in the Americas and the third-largest big cat in the world after the tiger and lion. It has a compact, muscular body, a broad head, and a golden coat covered with rosettes. Many people confuse jaguars with leopards, but jaguars are usually stockier and have stronger jaws.',
    speed: '50–80 km/h in short bursts',
    weight: '55–120 kg',
    size: '160–260 cm body length including tail',
    diet: 'Capybaras, deer, caimans, fish, turtles, peccaries',
    naturalHabitat: 'Rainforests, wetlands, river valleys, dry forests, grasslands',
    conservationStatus: 'Near Threatened',
    conservationNote: 'Monitored by IUCN Red List',
    facts: [
      'Jaguars have the strongest bite force of any big cat relative to body size.',
      'They often hunt near water and can catch fish, turtles, and caimans.',
      'A jaguar’s rosettes usually have small spots inside them, unlike leopard rosettes.',
      'Black jaguars are often called black panthers, but they are still jaguars.',
      'Jaguars are important apex predators in rainforest ecosystems.',
    ],
    image: null,
  },
  {
    id: 'leopard',
    scientificName: 'Panthera pardus',
    name: 'Leopard',
    status: 'Vulnerable',
    tag: 'Silent Climber',
    description:
      'The leopard is one of the most adaptable and mysterious big cats. It can live in forests, mountains, savannahs, deserts, and even near human settlements. Its spotted coat, silent movement, and flexible hunting style make it one of nature’s most successful ambush predators.',
    speed: '50–60 km/h',
    weight: '30–90 kg',
    size: '160–260 cm body length including tail',
    diet: 'Antelope, monkeys, birds, rodents, reptiles, small mammals',
    naturalHabitat: 'Forests, savannahs, mountains, deserts, scrublands',
    conservationStatus: 'Vulnerable',
    conservationNote: 'Monitored by IUCN Red List',
    facts: [
      'Leopards can carry prey heavier than themselves into trees.',
      'They are mostly solitary and extremely difficult to spot in the wild.',
      'Their rosette markings help them disappear into shadows and vegetation.',
      'Leopards are strong swimmers, although they are not as water-focused as jaguars.',
      'Black leopards are also called black panthers.',
    ],
    image: null,
  },
  {
    id: 'snow_leopard',
    scientificName: 'Panthera uncia',
    name: 'Snow Leopard',
    status: 'Vulnerable',
    tag: 'Mountain Ghost',
    description:
      'The snow leopard is one of the most elusive and beautiful big cats, perfectly adapted to life in cold mountain regions. Its pale smoky-gray coat, thick fur, long tail, and wide paws help it survive in rocky, snowy landscapes where few predators can live.',
    speed: '55–65 km/h in short bursts',
    weight: '25–55 kg',
    size: '180–230 cm body length including tail',
    diet: 'Blue sheep, ibex, marmots, hares, birds, mountain goats',
    naturalHabitat:
      'High mountains, rocky cliffs, alpine valleys, cold steppe regions',
    conservationStatus: 'Vulnerable',
    conservationNote: 'Monitored by IUCN Red List',
    facts: [
      'Snow leopards use their long tails for balance and as a warm wrap in freezing weather.',
      'Their wide paws act like natural snowshoes.',
      'They can leap several meters across rocky mountain terrain.',
      'Snow leopards cannot roar like lions or tigers.',
      'Their pale coat makes them almost invisible among rocks and snow.',
      'They are usually active at dawn, dusk, and night.',
    ],
    image: null,
  },
  {
    id: 'cheetah',
    scientificName: 'Acinonyx jubatus',
    name: 'Cheetah',
    status: 'Vulnerable',
    tag: 'Speed Specialist',
    description:
      'The cheetah is the fastest land animal, built for explosive acceleration rather than brute strength. Its slim body, long legs, flexible spine, deep chest, and semi-retractable claws allow it to sprint at incredible speed over short distances.',
    speed: '80–110 km/h in short sprints',
    weight: '20–65 kg',
    size: '180–230 cm body length including tail',
    diet: 'Gazelles, impalas, hares, young antelope, birds',
    naturalHabitat: 'Open grasslands, savannahs, dry plains, scrublands',
    conservationStatus: 'Vulnerable',
    conservationNote: 'Monitored by IUCN Red List',
    facts: [
      'Cheetahs can accelerate faster than most sports cars over a short distance.',
      'Their black “tear marks” may help reduce sun glare while hunting.',
      'Cheetahs cannot roar; they chirp, purr, growl, and hiss.',
      'They use their long tail like a steering tool while running.',
      'After a sprint, a cheetah must rest and cool down before eating.',
    ],
    image: null,
  },
  {
    id: 'cougar',
    scientificName: 'Puma concolor',
    name: 'Cougar',
    status: 'Least Concern',
    tag: 'Mountain Shadow',
    description:
      'The cougar, also known as the puma or mountain lion, is a powerful and highly adaptable wild cat found across the Americas. Although it is often grouped with big cats in popular apps and wildlife guides, it is not a roaring Panthera cat like lions, tigers, leopards, or jaguars.',
    speed: '64–80 km/h in short bursts',
    weight: '35–100 kg',
    size: '150–275 cm body length including tail',
    diet: 'Deer, elk, rabbits, raccoons, birds, small mammals',
    naturalHabitat: 'Mountains, forests, deserts, grasslands, rocky regions',
    conservationStatus: 'Least Concern',
    conservationNote: 'Monitored by IUCN Red List',
    facts: [
      'Cougars have many names, including puma, mountain lion, catamount, and panther.',
      'They cannot roar, but they can purr, growl, hiss, and scream.',
      'Cougars are excellent jumpers and can leap great distances.',
      'They have one of the widest ranges of any wild cat in the Americas.',
    ],
    image: null,
  },
  {
    id: 'clouded_leopard',
    scientificName: 'Neofelis nebulosa',
    name: 'Clouded Leopard',
    status: 'Vulnerable',
    tag: 'Forest Acrobat',
    description:
      'The clouded leopard is a mysterious forest cat with large cloud-shaped markings, a long tail, and unusually long canine teeth for its size. It is smaller than lions, tigers, and leopards, but its strength, climbing skill, and secretive behavior make it one of the most fascinating wild cats.',
    speed: '40–50 km/h',
    weight: '11–23 kg',
    size: '120–200 cm body length including tail',
    diet: 'Birds, monkeys, small deer, rodents, reptiles, small mammals',
    naturalHabitat:
      'Tropical forests, subtropical forests, dense woodland, mountain forests',
    conservationStatus: 'Vulnerable',
    conservationNote: 'Monitored by IUCN Red List',
    facts: [
      'Clouded leopards have some of the longest canine teeth relative to body size among wild cats.',
      'Their long tail helps them balance while climbing.',
      'They can climb down trees headfirst.',
      'Their cloud-like markings give them excellent camouflage in forest shadows.',
      'They are rarely seen in the wild because they are extremely secretive.',
    ],
    image: null,
  },
  {
    id: 'asiatic_lion',
    scientificName: 'Panthera leo persica',
    name: 'Asiatic Lion',
    status: 'Endangered',
    tag: 'Rare Royal Cat',
    description:
      'The Asiatic lion is a rare lion population found mainly in India’s Gir Forest region. It looks similar to the African lion but is usually slightly smaller, with a less developed mane in males and a noticeable fold of skin along the belly.',
    speed: '60–70 km/h in short bursts',
    weight: '110–190 kg',
    size: '240–290 cm body length including tail',
    diet: 'Deer, antelope, wild boar, livestock when natural prey is limited',
    naturalHabitat: 'Dry forests, scrublands, grasslands, open woodland',
    conservationStatus: 'Endangered',
    conservationNote: 'Monitored by IUCN Red List',
    facts: [
      'Asiatic lions live mainly in and around Gir Forest in India.',
      'Male Asiatic lions usually have shorter, thinner manes than many African lions.',
      'They have a visible belly fold that helps distinguish them from African lions.',
      'Their survival is considered one of India’s major conservation stories.',
      'Because they live in one main region, disease outbreaks can be especially dangerous for them.',
    ],
    image: null,
  },
  {
    id: 'black_panther',
    scientificName: 'Panthera pardus or Panthera onca',
    name: 'Black Panther',
    status: 'Depends on species',
    tag: 'Shadow Hunter',
    description:
      'A black panther is not a separate species. The name usually refers to a melanistic leopard in Africa or Asia, or a melanistic jaguar in the Americas. Melanism gives the animal a very dark coat, although its spots or rosettes can often still be seen in certain light.',
    speed: 'Depends on species',
    weight: 'Depends on species',
    size: 'Depends on species',
    diet: 'Deer, monkeys, birds, wild pigs, reptiles, smaller mammals',
    naturalHabitat: 'Rainforests, dense forests, wetlands, mountain forests',
    conservationStatus: 'Depends on species',
    conservationNote: 'Monitored by IUCN Red List',
    facts: [
      'A black panther is usually a black leopard or a black jaguar.',
      'The dark coat is caused by a genetic condition called melanism.',
      'Their spots are often still visible under strong light.',
      'Black panthers are especially associated with dense forests.',
      'They are not a separate big cat species.',
    ],
    image: null,
  },
  {
    id: 'sunda_clouded_leopard',
    scientificName: 'Neofelis diardi',
    name: 'Sunda Clouded Leopard',
    status: 'Vulnerable',
    tag: 'Island Forest Phantom',
    description:
      'The Sunda clouded leopard lives on the islands of Borneo and Sumatra. It was once considered the same species as the mainland clouded leopard, but scientists now recognize it as a separate species with its own unique genetic and physical traits.',
    speed: '40–50 km/h',
    weight: '12–26 kg',
    size: '130–210 cm body length including tail',
    diet: 'Monkeys, birds, deer, rodents, reptiles, small mammals',
    naturalHabitat:
      'Tropical rainforests, peat swamp forests, island forests, mountain forests',
    conservationStatus: 'Vulnerable',
    conservationNote: 'Monitored by IUCN Red List',
    facts: [
      'Sunda clouded leopards live only on Borneo and Sumatra.',
      'They are separate from mainland clouded leopards.',
      'Their long tail helps them move through trees with balance and control.',
      'They are among the least-seen wild cats in the world.',
    ],
    image: null,
  },
  {
    id: 'sumatran_tiger',
    scientificName: 'Panthera tigris sumatrae',
    name: 'Sumatran Tiger',
    status: 'Critically Endangered',
    tag: 'Island Survivor',
    description:
      'The Sumatran tiger is the smallest living tiger subspecies and the only surviving tiger population in Indonesia. It lives on the island of Sumatra, where dense rainforests, peat swamps, and rugged mountain areas create a challenging but rich environment for hunting and survival.',
    speed: '50–65 km/h',
    weight: '75–140 kg',
    size: '220–255 cm body length including tail',
    diet: 'Deer, wild boar, monkeys, birds, fish, smaller mammals',
    naturalHabitat:
      'Tropical rainforests, peat swamp forests, mountain forests, lowland forests',
    conservationStatus: 'Critically Endangered',
    conservationNote: 'Monitored by IUCN Red List',
    facts: [
      'Sumatran tigers are the smallest living tiger subspecies.',
      'Their dense stripes help them disappear into dark rainforest vegetation.',
      'They are strong swimmers and may hunt near rivers or swampy areas.',
      'Sumatran tigers are the last remaining tiger population in Indonesia.',
      'Their island home makes their survival especially vulnerable to habitat change.',
      'They often have a darker coat than Bengal or Amur tigers.',
    ],
    image: null,
  },
  {
    id: 'malayan_tiger',
    scientificName: 'Panthera tigris jacksoni',
    name: 'Malayan Tiger',
    status: 'Critically Endangered',
    tag: 'Rainforest Phantom',
    description:
      'The Malayan tiger is a rare tiger subspecies found in the forests of Peninsular Malaysia. It is slightly smaller than many mainland tigers, which helps it move through dense rainforest, thick undergrowth, and hilly terrain with agility and control.',
    speed: '50–65 km/h',
    weight: '75–150 kg',
    size: '230–280 cm body length including tail',
    diet: 'Deer, wild boar, tapirs, monkeys, birds, smaller mammals',
    naturalHabitat: 'Tropical rainforests, lowland forests, hill forests, dense jungle',
    conservationStatus: 'Critically Endangered',
    conservationNote: 'Monitored by IUCN Red List',
    facts: [
      'Malayan tigers live only in Peninsular Malaysia.',
      'They were officially recognized as a separate tiger subspecies in the early 2000s.',
      'Their smaller size helps them move through thick rainforest.',
      'They are extremely difficult to observe in the wild.',
      'The Malayan tiger is an important national symbol of Malaysia.',
    ],
    image: null,
  },
  {
    id: 'indochinese_tiger',
    scientificName: 'Panthera tigris corbetti',
    name: 'Indochinese Tiger',
    status: 'Endangered',
    tag: 'Hidden Jungle Hunter',
    description:
      'The Indochinese tiger is a secretive tiger subspecies that lives in parts of Southeast Asia. It is generally smaller and darker than the Bengal tiger, with narrower stripes and a body built for moving through forested hills, bamboo thickets, and remote jungle landscapes.',
    speed: '50–65 km/h',
    weight: '100–195 kg',
    size: '240–285 cm body length including tail',
    diet: 'Deer, wild boar, banteng, monkeys, porcupines, smaller mammals',
    naturalHabitat:
      'Tropical forests, hill forests, bamboo forests, remote mountain valleys',
    conservationStatus: 'Endangered',
    conservationNote: 'Monitored by IUCN Red List',
    facts: [
      'Indochinese tigers are among the most secretive tiger subspecies.',
      'Camera traps are often used to study them in remote forests.',
      'They usually have darker coats and narrower stripes than Bengal tigers.',
      'They need large, connected forests to survive.',
      'Their range has become much smaller than it once was.',
      'They are powerful ambush hunters that rely heavily on forest cover.',
    ],
    image: null,
  },
  {
    id: 'south_china_tiger',
    scientificName: 'Panthera tigris amoyensis',
    name: 'South China Tiger',
    status: 'Critically Endangered',
    tag: 'Lost Forest Legend',
    description:
      'The South China tiger is one of the most endangered tiger subspecies in the world. It once lived across parts of southern China, but today it is possibly extinct in the wild, with surviving individuals mainly found in captivity and conservation programs.',
    speed: '50–65 km/h',
    weight: '100–175 kg',
    size: '230–265 cm body length including tail',
    diet: 'Historically deer, wild boar, livestock, smaller mammals',
    naturalHabitat:
      'Historically subtropical forests, mountain forests, grasslands, river valleys',
    conservationStatus: 'Critically Endangered',
    conservationNote: 'Monitored by IUCN Red List',
    facts: [
      'The South China tiger may be extinct in the wild.',
      'It is considered one of the most ancient tiger lineages.',
      'Its stripes are often described as relatively narrow and widely spaced.',
      'Most living South China tigers are part of managed breeding programs.',
      'It is sometimes called the “Chinese tiger.”',
      'Its story is one of the most dramatic warnings in big cat conservation.',
    ],
    image: null,
  },
  {
    id: 'white_tiger',
    scientificName: 'Panthera tigris tigris',
    name: 'White Tiger',
    status: 'Not a separate wild subspecies',
    tag: 'Rare Color Morph',
    description:
      'The white tiger is not a separate species or subspecies. It is usually a Bengal tiger with a rare genetic color variation that produces a pale coat, dark stripes, and blue eyes.',
    speed: '49–65 km/h',
    weight: '140–300 kg',
    size: '270–310 cm body length including tail',
    diet: 'Deer, wild boar, water buffalo, monkeys, smaller mammals',
    naturalHabitat:
      'Historically the same habitats as Bengal tigers, but white tigers today are mainly seen in captivity',
    conservationStatus: 'Not classified as a separate wild taxon',
    conservationNote: 'Related species monitored by IUCN Red List',
    facts: [
      'White tigers are usually Bengal tigers with a rare genetic color trait.',
      'They are not albino because they still have dark stripes and blue eyes.',
      'White tigers are not a separate endangered subspecies.',
      'Their pale coat would make camouflage harder in many wild habitats.',
      'Most white tigers seen today live in captivity.',
    ],
    image: null,
  },
  {
    id: 'barbary_lion',
    scientificName: 'Panthera leo leo',
    name: 'Barbary Lion',
    status: 'Extinct in the Wild',
    tag: 'Atlas Mountain King',
    description:
      'The Barbary lion once lived across North Africa, including the Atlas Mountains and surrounding regions. It was famous for its impressive size, dark mane, and powerful appearance. Today, the Barbary lion is considered extinct in the wild.',
    speed: '60–80 km/h in short bursts',
    weight: '160–250 kg',
    size: '260–330 cm body length including tail',
    diet: 'Historically deer, wild boar, antelope, Barbary sheep, livestock',
    naturalHabitat:
      'Mountain forests, scrublands, semi-arid plains, Atlas Mountain regions',
    conservationStatus: 'Extinct in the Wild',
    conservationNote: 'Historical population monitored through conservation research',
    facts: [
      'Barbary lions once lived in North Africa.',
      'They were associated with the Atlas Mountains.',
      'Their dark, full mane made them especially famous.',
      'Ancient Romans used North African lions in arenas.',
      'No confirmed wild Barbary lions remain today.',
      'Some zoo lions may carry Barbary lion ancestry.',
    ],
    image: null,
  },
  {
    id: 'eurasian_lynx',
    scientificName: 'Lynx lynx',
    name: 'Eurasian Lynx',
    status: 'Least Concern',
    tag: 'Forest Listener',
    description:
      'The Eurasian lynx is the largest lynx species and one of the most impressive wild cats of Europe and Asia. It has long legs, a short tail, tufted ears, wide paws, and a spotted coat that blends beautifully into forest shadows and snowy landscapes.',
    speed: '50–65 km/h in short bursts',
    weight: '18–36 kg',
    size: '80–130 cm body length',
    diet: 'Roe deer, hares, birds, rodents, foxes, small mammals',
    naturalHabitat: 'Boreal forests, mountain forests, mixed woodlands, snowy regions',
    conservationStatus: 'Least Concern',
    conservationNote: 'Monitored by IUCN Red List',
    facts: [
      'The Eurasian lynx is the largest lynx species.',
      'Its ear tufts may help with communication and sound detection.',
      'Wide paws help it move across snow.',
      'It is very quiet and rarely seen by people.',
      'In some European regions, lynx have been successfully reintroduced.',
    ],
    image: null,
  },
  {
    id: 'canada_lynx',
    scientificName: 'Lynx canadensis',
    name: 'Canada Lynx',
    status: 'Least Concern',
    tag: 'Snowstep Hunter',
    description:
      'The Canada lynx is a northern forest cat specially adapted to cold, snowy environments. It has thick fur, long legs, large paws, and a short black-tipped tail.',
    speed: '40–50 km/h',
    weight: '8–17 kg',
    size: '75–110 cm body length',
    diet: 'Snowshoe hares, birds, squirrels, rodents, small mammals',
    naturalHabitat: 'Boreal forests, snowy woodlands, northern conifer forests',
    conservationStatus: 'Least Concern',
    conservationNote: 'Monitored by IUCN Red List',
    facts: [
      'Canada lynx have huge paws that work like snowshoes.',
      'Snowshoe hares are their main food source.',
      'Their population often rises and falls with hare numbers.',
      'Their thick fur protects them in freezing northern forests.',
      'They are usually solitary and avoid open areas.',
    ],
    image: null,
  },
  {
    id: 'caracal',
    scientificName: 'Caracal caracal',
    name: 'Caracal',
    status: 'Least Concern',
    tag: 'Desert Jumper',
    description:
      'The caracal is a medium-sized wild cat famous for its long black ear tufts, athletic body, and incredible jumping ability.',
    speed: '50–80 km/h in short bursts',
    weight: '8–19 kg',
    size: '60–110 cm body length including tail',
    diet: 'Birds, rodents, hares, small antelope, reptiles',
    naturalHabitat: 'Savannahs, dry scrublands, semi-deserts, rocky hills, open woodland',
    conservationStatus: 'Least Concern',
    conservationNote: 'Monitored by IUCN Red List',
    facts: [
      'Caracals can leap high enough to catch birds in midair.',
      'Their long black ear tufts are one of their most recognizable features.',
      'The name “caracal” comes from a word meaning “black ear.”',
      'They are mostly nocturnal in hot regions.',
      'Caracals are strong enough to hunt prey larger than themselves.',
      'They use their excellent hearing to locate hidden prey.',
    ],
    image: null,
  },
  {
    id: 'serval',
    scientificName: 'Leptailurus serval',
    name: 'Serval',
    status: 'Least Concern',
    tag: 'Tall-Grass Radar',
    description:
      'The serval is a slender African wild cat with long legs, large ears, a small head, and a beautifully spotted coat. Its body is perfectly designed for hunting in tall grass.',
    speed: '65–80 km/h in short bursts',
    weight: '7–18 kg',
    size: '85–125 cm body length including tail',
    diet: 'Rodents, birds, frogs, insects, reptiles, small mammals',
    naturalHabitat: 'Wetlands, savannahs, reed beds, grasslands, open woodland',
    conservationStatus: 'Least Concern',
    conservationNote: 'Monitored by IUCN Red List',
    facts: [
      'Servals have some of the longest legs relative to body size among cats.',
      'Their large ears help them hear prey moving underground or in tall grass.',
      'They can leap high into the air before pouncing.',
      'Servals are extremely successful hunters compared with many other cats.',
      'They often live near water and grassy wetlands.',
    ],
    image: null,
  },
  {
    id: 'fishing_cat',
    scientificName: 'Prionailurus viverrinus',
    name: 'Fishing Cat',
    status: 'Vulnerable',
    tag: 'Wetland Stalker',
    description:
      'The fishing cat is a strong, stocky wild cat that lives near wetlands, rivers, mangroves, and marshes. Unlike many cats that avoid water, fishing cats are skilled at catching fish and other water-dwelling prey.',
    speed: '35–45 km/h',
    weight: '5–16 kg',
    size: '75–115 cm body length including tail',
    diet: 'Fish, frogs, crabs, birds, rodents, reptiles, smaller mammals',
    naturalHabitat: 'Wetlands, mangroves, marshes, riverbanks, reed beds',
    conservationStatus: 'Vulnerable',
    conservationNote: 'Monitored by IUCN Red List',
    facts: [
      'Fishing cats are excellent swimmers.',
      'They often hunt near water and can catch fish, turtles, and caimans.',
      'They may tap the water surface to attract fish, then strike quickly.',
      'Their dense fur helps protect them in wet environments.',
      'They are strongly dependent on healthy wetlands.',
    ],
    image: null,
  },
];

